using System;
using Problem1;

namespace Problem2
{
    public class TestEmployeeDAO
    {
        public static void Main()
        {
            /* 1. Inserts an employee */
            EmployeeDAO.Add(new Employee()
            {
                FirstName = "TestingFirstName",
                MiddleName = "TestingMiddleName",
                LastName = "TestingLastName",
                JobTitle = "Haha",
                HireDate = DateTime.Now,
                AddressID = 4,
                DepartmentID = 5,
                Salary = 2345
            });

            /* 2. Prints his/her primary key generated by the DB */
            var lastEmployeeCreated = EmployeeDAO.LastEmployee();

            Console.WriteLine("Last Employee primary key: " + lastEmployeeCreated.EmployeeID);

            /* 3. Changes the employee first name and saves it to the database */
            lastEmployeeCreated.FirstName = "TestingFirstNameChange";
            EmployeeDAO.Modify(lastEmployeeCreated);

            /* 4. Deletes an employee */
            EmployeeDAO.Delete(lastEmployeeCreated);

            Console.ReadLine();
        }
    }
}
